// Prep step for design-sync. This project is a Claude Design folder, not an npm
// package: components live as plain .jsx + hand-written .d.ts + .prompt.md under
// components/<group>/. The converter (package-build.mjs) wants a package with a
// built dist entry and a types root, so this script synthesizes exactly that -
// deterministically, from the files already in the repo. Nothing here is a
// second source of truth: dist/ and .design-sync/docs/ are pure derivations.
//
// Run before every package-build.mjs run:  node .design-sync/prep.mjs
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, existsSync, symlinkSync, lstatSync } from 'node:fs';
import { join, basename } from 'node:path';
import * as esbuild from '../.ds-sync/node_modules/esbuild/lib/main.js';

const ROOT = process.cwd();
const GROUPS = readdirSync(join(ROOT, 'components'), { withFileTypes: true })
  .filter((d) => d.isDirectory()).map((d) => d.name).sort();

// -- 0a. self-link. copyTokens() resolves cfg.tokensGlob inside
// node_modules/<cfg.tokensPkg>, and this DS's tokens live in the package
// itself, so the package has to be resolvable by its own name. npm prunes this
// link as "extraneous" on any install, so recreate it every run rather than
// relying on it surviving. Junction, not symlink: no admin rights needed.
const LINK = join(ROOT, 'node_modules', 'agreement-vault-design-system');
let linkOk = false;
try { linkOk = existsSync(join(LINK, 'package.json')); } catch {}
if (!linkOk) {
  try { rmSync(LINK, { recursive: true, force: true }); } catch {}
  mkdirSync(join(ROOT, 'node_modules'), { recursive: true });
  symlinkSync(ROOT, LINK, 'junction');
  console.error('prep: recreated node_modules self-link (npm prunes it on install)');
}

const comps = [];
for (const g of GROUPS) {
  for (const f of readdirSync(join(ROOT, 'components', g)).sort()) {
    if (!f.endsWith('.jsx')) continue;
    const name = basename(f, '.jsx');
    comps.push({ name, group: g, jsx: `components/${g}/${name}.jsx`,
      dts: `components/${g}/${name}.d.ts`, doc: `components/${g}/${name}.prompt.md` });
  }
}
if (!comps.length) { console.error('prep: no components found'); process.exit(1); }

// -- 0. staged tokens: every token file EXCEPT fonts.css. The @font-face file
// is handed to cfg.extraFonts instead, which copies the binaries into fonts/
// and rewrites the url()s; copying it here too would ship a second, dangling
// copy pointing at ../assets/fonts/.
rmSync(join(ROOT, '.design-sync/tokens'), { recursive: true, force: true });
mkdirSync(join(ROOT, '.design-sync/tokens'), { recursive: true });
let tokCount = 0;
for (const f of readdirSync(join(ROOT, 'tokens')).sort()) {
  if (!f.endsWith('.css') || f === 'fonts.css') continue;
  writeFileSync(join(ROOT, '.design-sync/tokens', f), readFileSync(join(ROOT, 'tokens', f)));
  tokCount++;
}

// -- 1. docs root the converter's discovery can slug-match (<Name>.md) -------
rmSync(join(ROOT, '.design-sync/docs'), { recursive: true, force: true });
mkdirSync(join(ROOT, '.design-sync/docs'), { recursive: true });
let docCount = 0;
for (const c of comps) {
  if (!existsSync(join(ROOT, c.doc))) { console.error(`  ! no prompt.md for ${c.name}`); continue; }
  const body = readFileSync(join(ROOT, c.doc), 'utf8').replace(/^---\n[\s\S]*?\n---\n/, '');
  const title = c.group[0].toUpperCase() + c.group.slice(1);
  writeFileSync(join(ROOT, '.design-sync/docs', `${c.name}.md`),
    `---\ncategory: ${title}\n---\n\n${body.trimEnd()}\n`);
  docCount++;
}

// -- 2. types root: one flat barrel from the hand-written per-component .d.ts.
// Imports are hoisted (duplicate `import * as React` would redeclare) and
// declared type names are checked for collisions across files.
const IMPORT_RX = /^\s*import\s[^\n]*?;\s*$/gm;
const DECL_RX = /^export\s+(?:interface|type|function|const|class)\s+([A-Za-z0-9_$]+)/gm;
const seen = new Map();
let body = '';
for (const c of comps) {
  const raw = readFileSync(join(ROOT, c.dts), 'utf8');
  for (const m of raw.matchAll(DECL_RX)) {
    if (seen.has(m[1])) console.error(`  ! duplicate exported type "${m[1]}" in ${c.dts} (also ${seen.get(m[1])})`);
    else seen.set(m[1], c.dts);
  }
  body += `\n// ---- ${c.group}/${c.name} ${'-'.repeat(Math.max(0, 60 - c.name.length))}\n`
       +  raw.replace(IMPORT_RX, '').trim() + '\n';
}
mkdirSync(join(ROOT, 'dist'), { recursive: true });
writeFileSync(join(ROOT, 'dist/index.d.ts'),
  `// GENERATED by .design-sync/prep.mjs from components/*/*.d.ts - do not edit.\n`
  + `import * as React from "react";\n${body}`);

// -- 3. dist entry: one ESM bundle of every component, React external. -------
const barrel = comps.map((c) => `export * from ${JSON.stringify('../' + c.jsx)};`).join('\n') + '\n';
writeFileSync(join(ROOT, 'dist/.barrel.jsx'), barrel);
await esbuild.build({
  entryPoints: [join(ROOT, 'dist/.barrel.jsx')],
  outfile: join(ROOT, 'dist/index.js'),
  bundle: true, format: 'esm', platform: 'browser', jsx: 'transform',
  external: ['react', 'react-dom'], logLevel: 'warning',
});
// Components exported from a shared file (Marker lives in FindingRow.jsx) have no
// sibling prompt.md - their docs are authored under docs-extra/ and copied verbatim.
for (const f of (existsSync(join(ROOT, '.design-sync/docs-extra'))
  ? readdirSync(join(ROOT, '.design-sync/docs-extra')) : [])) {
  if (!f.endsWith('.md')) continue;
  writeFileSync(join(ROOT, '.design-sync/docs', f),
    readFileSync(join(ROOT, '.design-sync/docs-extra', f)));
  docCount++;
}

console.error(`prep: ${comps.length} components, ${docCount} docs, ${tokCount} token files, ${seen.size} exported types`);
console.error(`      groups: ${GROUPS.join(', ')}`);
